salt_observer/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.decorators import login_required

from .views import (
    Login, Logout,
    Dashboard, VisualNetwork,
    MinionList, MinionDetail, MinionEdit,
    NetworkList, NetworkDetail, NetworkEdit,
    DomainList, DomainDetail, DomainEdit,
    EventView, JobView, JobDetailView
)


def auth_url(regex, view, *args, **kwargs):
    return url(regex, login_required(view), *args, **kwargs)


urlpatterns = [
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', admin.site.urls),

    url(r'^login/$', Login.as_view(), name='login'),
    url(r'^logout/$', Logout.as_view(), name='logout'),

    auth_url(r'^$', Dashboard.as_view(), name='dashboard'),
    auth_url(r'^visual-network/$', VisualNetwork.as_view(), name='visual-network'),

    auth_url(r'^minions/$', MinionList.as_view(), name='minion-list'),
    auth_url(r'^minions/(?P<slug>[a-zA-Z0-9\.\-]+)/$', MinionDetail.as_view(), name='minion-detail'),
    auth_url(r'^minions/(?P<slug>[a-zA-Z0-9\.\-]+)/edit/$', MinionEdit.as_view(), name='minion-edit'),

    auth_url(r'^networks/$', NetworkList.as_view(), name='network-list'),
    auth_url(r'^networks/(?P<slug>[a-zA-Z0-9\.\-]+)/$', NetworkDetail.as_view(), name='network-detail'),
    auth_url(r'^networks/(?P<slug>[a-zA-Z0-9\.\-]+)/edit/$', NetworkEdit.as_view(), name='network-edit'),

    auth_url(r'^domains/$', DomainList.as_view(), name='domain-list'),
    auth_url(r'^domains/(?P<slug>[a-zA-Z0-9\.\-]+)/$', DomainDetail.as_view(), name='domain-detail'),
    auth_url(r'^domains/(?P<slug>[a-zA-Z0-9\.\-]+)/edit/$', DomainEdit.as_view(), name='domain-edit'),

    auth_url(r'^events/$', EventView.as_view(), name='events'),
    auth_url(r'^jobs/$', JobView.as_view(), name='job-list'),
    auth_url(r'^jobs/(?P<jid>[0-9]+)$', JobDetailView.as_view(), name='job-detail'),
]

salt_observer/models.py
from django.db import models
from django.conf import settings

import json
import requests


class MarkdownContent(models.Model):
    ''' To enable on-the-fly modification of templates '''

    md_content = models.TextField(default='', blank=True)
    md_last_edited = models.DateTimeField(blank=True, null=True)
    md_last_autor = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True)

    class Meta:
        abstract = True


class Network(MarkdownContent):
    ''' Representation of an Network '''

    ipv4 = models.CharField(max_length=15)
    mask = models.CharField(max_length=15)

    last_updated = models.DateTimeField()

    def __str__(self):
        return self.ipv4


class Domain(MarkdownContent):
    ''' Represents a Fully qualified domain name '''

    fqdn = models.CharField(max_length=255)
    minion = models.ManyToManyField('Minion', blank=True)
    _ssl_lab_status = models.TextField(default='{}')

    can_speak_https = models.BooleanField(help_text='Is there a service listening on port 443')
    public = models.BooleanField(help_text='Is this domain public accessible')
    valid = models.BooleanField()

    @property
    def ssl_lab_status(self):
        try:
            return json.loads(self._ssl_lab_status)
        except ValueError:
            return dict()

    @ssl_lab_status.setter
    def ssl_lab_status(self, value):
        self._ssl_lab_status = json.dumps(value)

    def check_if_valid(self, commit=True):
        try:
            a = requests.get('http://{}/'.format(self.fqdn), timeout=5, verify=False)
            b = requests.get('https://{}/'.format(self.fqdn), timeout=5, verify=False)
        except (requests.exceptions.ConnectionError, requests.exceptions.Timeout):
            self.valid = False
        else:
            self.valid = True

        if commit:
            self.save()

    def minion_count(self):
        return len(self.minion.all())

    def worst_grade(self):
        if self.ssl_lab_status.get('grades', []):
            return max([g for g in self.ssl_lab_status.get('grades', [])])
        return '0'

    def save(self, *args, **kwargs):
        if not self.id:
            self.check_if_valid(commit=False)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.fqdn


class Minion(MarkdownContent):
    ''' Representation of a Server in Salt '''

    fqdn = models.CharField(max_length=255)
    networks = models.ManyToManyField(Network, through='NetworkInterface')
    _data = models.TextField(default='{}')

    last_updated = models.DateTimeField()

    @property
    def data(self):
        try:
            return json.loads(self._data)
        except ValueError:
            return dict()

    @data.setter
    def data(self, value):
        self._data = json.dumps(value)

    def update_data(self, value):
        ''' In order to update self.data without 3 lines of code
            self.data.update() wont work!
        '''
        data = self.data
        data.update(value)
        self.data = data

    @property
    def user_count(self):
        return len(self.data.get('grains', {}).get('users', []))

    @property
    def package_count(self):
        return len(self.data.get('packages', []))

    @property
    def network_count(self):
        return len(self.networks.all())

    def outdated_package_count(self):
        return len([p for p, v in self.data.get('packages', {}).items() if v['latest_version']])

    def fullest_partition_percentage(self):
        try:
            return max([p.get('percent', 0) for p in self.data.get('mounted_devices', [])])
        except (AttributeError, ValueError):
            return 0

    def __str__(self):
        return self.fqdn


class NetworkInterface(models.Model):
    ''' Representing a network card '''

    network = models.ForeignKey(Network, on_delete=models.CASCADE)
    minion = models.ForeignKey(Minion, on_delete=models.CASCADE)

    name = models.CharField(max_length=255)
    ip_address = models.CharField(max_length=17)
    mac_address = models.CharField(max_length=17)

    def __str__(self):
        return '{} ({})'.format(self.name, self.mac_address)

salt_observer/forms.py
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import ugettext, ugettext_lazy as _

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Div, Field, HTML
from crispy_forms.bootstrap import StrictButton, PrependedText

from salt_observer.models import (
    Domain, Minion, Network
)


class MarkdownFormMixin(forms.ModelForm):

    md_content = forms.CharField(
        widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 15, 'autofocus': 'True', 'placeholder': '# Some Markdown'}),
        label='',
        required=False
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.form_method = 'post'

        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = ''
        self.helper.field_class = 'col-lg-12'

        self.helper.layout = Layout(
            Div(Field('md_content')),
            Div(StrictButton('Save', type='submit', css_class='btn-primary'))
        )

    class Meta:
        abstract = True
        fields = ['md_content']


class LoginForm(AuthenticationForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.error_messages.update({
            'invalid_login': _(
                'Please enter a corrent %(username)s and password. '
                'Note that these credentials must be a valid api user!'
            )
        })

        self.fields['username'].widget.attrs.update({'autofocus': 'True'})
        self.helper = FormHelper()
        self.helper.form_method = 'post'

        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = ''
        self.helper.field_class = 'col-lg-12'

        self.helper.layout = Layout(
            PrependedText('username', '<i class="fa fa-user fa-fw"></i>', placeholder='Username'),
            PrependedText('password', '<i class="fa fa-unlock-alt fa-fw"></i>', placeholder='Password'),
            Div(
                Div(
                    StrictButton('Login', type='submit', css_class='btn-default btn-block'),
                    css_class='col-lg-12',
                ),
                css_class='form-group'
            )
        )

    username = forms.CharField(label='', max_length=255)
    password = forms.CharField(label='', widget=forms.PasswordInput)

    def clean(self):
        '''
            Overwriting this method to pass the current request down to the
            backends via authenticate([...])
        '''
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username and password:
            self.user_cache = authenticate(
                username=username,
                password=password,
                request=self.request
            )
            if self.user_cache is None:
                raise forms.ValidationError(
                    self.error_messages['invalid_login'],
                    code='invalid_login',
                    params={'username': self.username_field.verbose_name},
                )
            else:
                self.confirm_login_allowed(self.user_cache)

        return self.cleaned_data


class MinionEditForm(MarkdownFormMixin):
    class Meta:
        model = Minion
        fields = ['md_content']


class NetworkEditForm(MarkdownFormMixin):
    class Meta:
        model = Network
        fields = ['md_content']


class DomainEditForm(MarkdownFormMixin):
    class Meta:
        model = Domain
        fields = ['md_content']

salt_observer/views.py
from django.contrib.auth.models import User
from django.template import Context, Template
from django.views.generic import View, TemplateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import FormView, UpdateView
from django.core.urlresolvers import reverse_lazy
from django.utils import timezone
from django.utils.safestring import mark_safe
from django.contrib.auth import login, logout
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.conf import settings

import json
from markdown import Markdown
from collections import OrderedDict
from dateutil.parser import parse as dateparse

from salt_observer.saltapis import SaltTornado
from salt_observer.forms import (
    LoginForm,
    MinionEditForm, NetworkEditForm, DomainEditForm
)
from salt_observer.models import (
    Minion, Network, Domain
)


class MarkdownEditMixin(object):

    def form_valid(self, form, *args, **kwargs):
        result = super().form_valid(form, *args, **kwargs)
        obj = self.get_object()

        obj.md_content = form.cleaned_data.get('md_content', '')
        obj.md_last_autor = self.request.user
        obj.md_last_edited = timezone.now()
        obj.save()

        return result

    def get_success_url(self, *args, **kwargs):
        return reverse_lazy(self.success_url_name, args=[self.kwargs.get('slug', '')])


class Login(FormView):
    template_name = 'auth/login.html'
    form_class = LoginForm
    success_url = '/'

    def form_valid(self, form, *args, **kwargs):
        login(self.request, form.get_user())
        return super().form_valid(form, *args, **kwargs)

    def get_form_kwargs(self, *args, **kwargs):
        '''dirty hack to pass the current request down to the backends'''
        kwargs = super().get_form_kwargs(*args, **kwargs)
        kwargs['request'] = self.request
        return kwargs

    def get_success_url(self):
        return self.request.GET.get('next', reverse_lazy('dashboard'))

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_authenticated():
            return HttpResponseRedirect(reverse_lazy('dashboard'))
        else:
            return super().dispatch(request, *args, **kwargs)


class Logout(View):

    def dispatch(self, request, *args, **kwargs):
        logout(request)
        return HttpResponseRedirect(reverse_lazy('dashboard'))


class Dashboard(TemplateView):
    template_name = 'home/dashboard.html'

    def get_context_data(self, *args, **kwargs):
        all_minions = Minion.objects.all()
        all_networks = Network.objects.all()
        all_domains = Domain.objects.all()

        ctx = super().get_context_data(*args, **kwargs)
        ctx.update({
            'all_minions': all_minions,
            'all_networks': all_networks,
            'all_domains': all_domains,
            'all_users': User.objects.all(),
            'w5_outdated_minions': sorted(all_minions, key=lambda m: m.outdated_package_count(), reverse=True)[:5],
            'w5_fullest_minions': sorted(all_minions, key=lambda m: m.fullest_partition_percentage(), reverse=True)[:5],
            'w5_domain_ssl_grades': sorted(all_domains, key=lambda d: d.worst_grade(), reverse=True)[:5],
        })
        return ctx


class VisualNetwork(TemplateView):
    template_name = 'home/visual_network.html'

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        ctx.update({
            'minions': Minion.objects.all(),
            'networks': Network.objects.all().exclude(ipv4=settings.SALT_NETWORK),
        })
        return ctx


class MinionList(ListView):
    template_name = 'minion/list.html'
    model = Minion


class MinionDetail(DetailView):
    template_name = 'minion/detail.html'
    model = Minion
    slug_field = 'fqdn'


class MinionEdit(MarkdownEditMixin, UpdateView, MinionDetail):
    template_name = 'minion/edit.html'
    form_class = MinionEditForm
    success_url_name = 'minion-detail'


class NetworkList(ListView):
    template_name = 'network/list.html'
    model = Network


class NetworkDetail(DetailView):
    template_name = 'network/detail.html'
    model = Network
    slug_field = 'ipv4'


class NetworkEdit(MarkdownEditMixin, UpdateView, NetworkDetail):
    template_name = 'network/edit.html'
    form_class = NetworkEditForm
    success_url_name = 'network-detail'


class DomainList(ListView):
    template_name = 'domain/list.html'
    model = Domain


class DomainDetail(DetailView):
    template_name = 'domain/detail.html'
    model = Domain
    slug_field = 'fqdn'


class DomainEdit(MarkdownEditMixin, UpdateView, DomainDetail):
    template_name = 'domain/edit.html'
    form_class = DomainEditForm
    success_url_name = 'domain-detail'


class AbstractTornadoView(TemplateView):

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context.update({
            'tornado_host': settings.SALT['api']['tornado']['host'],
            'tornado_port': settings.SALT['api']['tornado']['port'],
        })
        return context


class EventView(AbstractTornadoView):
    template_name = 'events.html'


class JobView(AbstractTornadoView):
    template_name = 'jobs/index.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context.update({
            'job_list': self.transform_jobs(self.get_jobs())
        })
        return context

    def get_jobs(self):
        return SaltTornado(
            token=self.request.session['salt_tornado_token']
        ).request(
            resource='/jobs/'
        ).json().get('return')[0]

    def transform_jobs(self, jobs):
        transformed_jobs = dict()

        for key, value in jobs.items():
            value['StartTime'] = dateparse(value['StartTime'])
            if not value['Function'] in settings.SALT['jobs']['ignore']:
                transformed_jobs.update({key: value})

        return OrderedDict(sorted(transformed_jobs.items(), reverse=True))


class JobDetailView(AbstractTornadoView):
    template_name = 'jobs/detail.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context.update({
            'job_details': SaltTornado(
                token=self.request.session['salt_tornado_token']
            ).request(
                resource='/jobs/' + str(kwargs['jid']),
            ).json().get('return')[0]
        })
        return context

salt_observer/templates/network/detail.html
{% extends '_layout/navbar.html' %}
{% load utils %}

{% block nav-networks %}class="active"{% endblock %}
{% block title-extra %}{{ network.ipv4 }}{% endblock %}

{% block post-script %}
    <script type="text/javascript">
        $('#miniontable').filterTable({
            inputSelector: '#miniontable-search',
        });
    </script>
{% endblock %}

{% block content %}
    <div class="page-header">
        <h1>{{ network.ipv4 }}</h1>
    </div>

    <div class="row">
        <div class="col-md-12">

            <ul class="nav nav-tabs" role="tablist">
                <li role="presentation" class="active"><a href="#general" aria-controls="general" role="tab" data-toggle="tab">General</a></li>
                <li role="presentation"><a href="#minions" aria-controls="minions" role="tab" data-toggle="tab">Connected minions</a></li>
            </ul>

            <!-- tab panes -->
            <div class="tab-content">

                <!-- general -->
                <div role="tabpanel" class="tab-pane fade in active" id="general">
                    <div class="row">
                        <div class="col-md-8">
                            {% block general-tab %}

                                <a class="text-muted pull-right" href="{% url 'network-edit' network.ipv4 %}"><i class="fa fa-2x fa-pencil"></i></a>

                                {% if network.md_content %}
                                    <div>
                                        {{ network.md_content|markdownify }}
                                    </div>
                                    <hr>
                                    <div class="footnote">
                                        <i class="text-muted">Last edited {{ network.md_last_edited|date:"d.m.y - H:i" }} from {{ network.md_last_autor.username }}</i>
                                    </div>
                                {% else %}
                                    <i class="text-muted">No special information about this network yet. But you can <a href="{% url 'network-edit' network.ipv4 %}">edit</a> this section!</i>
                                {% endif %}

                            {% endblock %}
                        </div>
                        <div class="col-md-4">
                            <table class="table datatable">
                                <tbody>
                                    <tr>
                                        <td>Network</td>
                                        <td>{{ network.ipv4 }}</td>
                                    </tr>
                                    <tr>
                                        <td>Subnetmask</td>
                                        <td>{{ network.mask }}</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

                <!-- minions -->
                <div role="tabpanel" class="tab-pane fade" id="minions">
                    <div class="row margin-bottom-wrapper">
                        <div class="col-md-6">
                            <div class="input-group">
                                <span class="input-group-addon"><i class="fa fa-search fa-fw"></i></span>
                                <input id="miniontable-search" class="form-control" placeholder="Suchen nach ..." type="search">
                            </div>
                        </div>
                    </div>
                    <table id="miniontable" class="table sortable">
                        <thead>
                            <tr>
                                <th>Minion Fqdn</th>
                                <th>Minion IP</th>
                                <th>Network interfaces</th>
                                <th>MAC address</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for minion in network.minion_set.all %}
                                <tr>
                                    <td><a href="{% url 'minion-detail' minion.fqdn %}">{{ minion.fqdn }}</a></td>
                                    {% for ni in minion.networkinterface_set.all %}
                                        {% if ni.network.ipv4 == network.ipv4 %}
                                            <td>{{ ni.ip_address }}</td>
                                            <td>{{ ni.name }}</td>
                                            <td>{{ ni.mac_address }}</td>
                                        {% endif %}
                                    {% endfor %}
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>

            </div>
        </div>
    </div>
{% endblock %}

salt_observer/templates/network/edit.html
{% extends 'network/detail.html' %}
{% load crispy_forms_tags %}

{% block nav-networks %}class="active"{% endblock %}
{% block title-extra %}Edit | {{ network.ipv4 }}{% endblock %}

{% block general-tab %}
    {% crispy form %}
{% endblock %}

salt_observer/templates/network/list.html
{% extends '_layout/navbar.html' %}
{% load staticfiles %}

{% block nav-networks %}class="active"{% endblock %}
{% block title-extra %}Networks{% endblock %}

{% block post-script %}
    <script>
        $(function() {
            $.tablesorter.themes.bootstrap = {
                header: 'bootstrap-header',
                iconSortNone: 'fa fa-sort',
                iconSortAsc: 'fa fa-sort-asc',
                iconSortDesc: 'fa fa-sort-desc',
            };
            $("#network-table").tablesorter({
                theme: "bootstrap",
                headerTemplate: '{content} {icon}',
                sortList: [[0,0]],
                widgets: ["uitheme"],
            });
            $("#network-table").filterTable({
                inputSelector: '#network-table-filter',
            });
        })
    </script>
{% endblock %}

{% block content %}
    <div class="page-header">
        <h1>Networks</h1>
    </div>
    <div class="row margin-bottom-wrapper">
        <div class="col-md-3">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-search fa-fw"></i></span>
                <input id="network-table-filter" class="form-control" placeholder="Suchen nach ..." type="search">
            </div>
        </div>
    </div>

    <table id="network-table" class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Network</th>
                <th>Subnet mask</th>
                <th>Connected Minions</th>
            </tr>
        </thead>
        <tbody>
            {% for network in network_list %}
                <tr>
                    <td><a href="{% url 'network-detail' network.ipv4 %}">{{ network.ipv4 }}</a></td>
                    <td>{{ network.mask }}</td>
                    <td>{{ network.minion_set.all|length }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}